### ISSUE TITLE
Major World Corruption Issue

### ISSUE THREAD

**Issue by SlimefrogSocial** [Harleyoc1/DynamicTreesTraverse#1]
I have pre-generated a few thousand chunk radius on my server. We have found many fir tree forest mountains and many other biomes. When we started exploring more north, we ran into Birch Forested Hills. The server has been crashing with Exception Ticking World ever since. Can you help me fix this?
Using latest Dynamic Trees and Dynamic Trees for Traverse and Traverse Legacy Continued. 

Log:

[latest.log](https://github.com/Harleyoc1/DynamicTreesTraverse/files/5556022/latest.log)

Crash Log:

[crash-2020-11-17_15.22.42-server.txt](https://github.com/Harleyoc1/DynamicTreesTraverse/files/5556024/crash-2020-11-17_15.22.42-server.txt)

https://pastebin.com/uucghVtR

**Comment by SlimefrogSocial** [comment]
pregen and sponge and a bunch of complicated stuff, but its resolved

**Comment by SlimefrogSocial** [comment]
Sponge was crashing pregen which was killing dynamic trees which was corrupting the world. Now, I have removed sponge and pregen went on without a hitch, but it now has crashed again...

**Comment by Harleyoc1** [comment]
Logs please?

**Comment by Harleyoc1** [comment]
That is if they actually reveal anything different this time...

**Comment by SlimefrogSocial** [comment]
Ok, i need to do testing and i cant submit atm, but i may have found that BiomeTweaker is breaking them now, be back later or tomorrow

**Comment by SlimefrogSocial** [comment]
[debug.log](https://github.com/Harleyoc1/DynamicTreesTraverse/files/5563611/debug.log)


[latest.log](https://github.com/Harleyoc1/DynamicTreesTraverse/files/5563600/latest.log)

[crash-2020-11-18_19.58.24-server.txt](https://github.com/Harleyoc1/DynamicTreesTraverse/files/5563647/crash-2020-11-18_19.58.24-server.txt)

Its not biome tweaker it just crashed again, roofed forest biome

**Comment by Harleyoc1** [comment]
I can’t see any evidence that this is specifically related to DT traverse... Do you mind trying to pregenerate a world with just DT and DT traverse and seeing if it still crashes like this without all the other mods?

**Comment by SlimefrogSocial** [comment]
I agree, it may be a DT in general (any addons will have same issue because they all use the same base) and I think it may be Recurrent Complex messing with tree gen... I will do more testing by removing all mods from the server except dt and see what happens! Thank you for your time, I will close and relocate to DT issues for documentation purpose!
https://github.com/ferreusveritas/DynamicTrees/issues/466

**Comment by SlimefrogSocial** [comment]
I FIXED IT. Incompatibility with ThutTech (Thuts Elevators). Not really using thuts mods so I'll just remove them
